# syntax=docker/dockerfile:1
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Stage 1: build the thin RangerHugeGraphService jar
FROM --platform=$BUILDPLATFORM maven:3.9.0-eclipse-temurin-11 AS build

WORKDIR /pkg

COPY . .

RUN --mount=type=cache,target=/root/.m2 \
    mvn package -pl hugegraph-server/hugegraph-ranger-plugin -am -e -B -ntp \
        -Dmaven.test.skip=true \
        -Dmaven.javadoc.skip=true \
        -Drat.skip=true \
        -Dcheckstyle.skip=true

# Stage 2: bake the jar into the stock Ranger Admin image
FROM apache/ranger:2.9.0

LABEL maintainer="HugeGraph Docker Maintainers <dev@hugegraph.apache.org>"

# apache/ranger:2.9.0 ships Java 8, but RangerHugeGraphService (loaded directly by
# Ranger Admin's JVM, see implClass in ranger-servicedef-hugegraph.json) is compiled
# to Java 11 bytecode by the parent hugegraph POM, causing "class file version 55.0
# ... only recognizes ... up to 52.0". Install Java 11 alongside the bundled Java 8
# and repoint JAVA_HOME so Ranger Admin (and setup.sh's version check) run on it.
ARG TARGETARCH
USER root
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
       openjdk-11-jdk-headless \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk-${TARGETARCH}
ENV PATH=${JAVA_HOME}/bin:$PATH
USER ranger

RUN mkdir -p /opt/ranger/ranger-2.9.0-admin/ews/webapp/WEB-INF/classes/ranger-plugins/hugegraph

COPY --from=build --chown=ranger:ranger /pkg/hugegraph-server/hugegraph-ranger-plugin/target/hugegraph-ranger-plugin-1.7.0.jar \
    /opt/ranger/ranger-2.9.0-admin/ews/webapp/WEB-INF/classes/ranger-plugins/hugegraph/hugegraph-ranger-plugin.jar
